version "4.14"

// Base Flashlight Data Classes
#include "zscript/accensus/flashlight/Beams.zsc"
#include "zscript/accensus/flashlight/Mounts.zsc"
#include "zscript/accensus/flashlight/Lights.zsc"

#include "zscript/accensus/flashlight/Handlers.zsc"


// Items, Decorations, etc.
#include "zscript/accensus/decorations/floodLamp/FloodLamp.zsc"
#include "zscript/accensus/decorations/Worklight/Worklight.zsc"
#include "zscript/accensus/items/flashlight/Flashlight.zsc"
